# Generated by Django 5.2.4 on 2025-07-04 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='arbitro',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='goles_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='goles_visitante',
        ),
        migrations.AlterUniqueTogether(
            name='tablaposicion',
            unique_together={('torneo', 'equipo')},
        ),
        migrations.AlterField(
            model_name='eventopartido',
            name='jugador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campeonato.jugador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventopartido',
            name='tipo_evento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='campeonato.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='campeonato.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='estadio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campeonato.estadio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablaposicion',
            name='goles_contra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablaposicion',
            name='goles_favor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablaposicion',
            name='jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablaposicion',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='tablaposicion',
            name='empatados',
        ),
        migrations.RemoveField(
            model_name='tablaposicion',
            name='ganados',
        ),
        migrations.RemoveField(
            model_name='tablaposicion',
            name='perdidos',
        ),
    ]
